//User Reducer Types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_USER = 'SET_USER'
export const LOADING_USER = 'LOADING_USER'
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ'

//UI Reducer Types
export const SET_ERRORS = 'SET_ERRORS'
export const LOADING_UI = 'LOADING_UI'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const LOADING_DATA = 'LOADING_DATA'
export const STOP_LOADING_UI = 'STOP_LOADING_UI'

//Data Reducer Types
export const SET_BUBBLES = 'SET_BUBBLES'
export const SET_BUBBLE = 'SET_BUBBLE'
export const LIKE_BUBBLE = 'LIKE_BUBBLE'
export const UNLIKE_BUBBLE = 'UNLIKE_BUBBLE'
export const DELETE_BUBBLE = 'DELETE_BUBBLE'
export const POST_BUBBLE = 'POST_BUBBLE'
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'